name: simple_dart_text_area_field
description: Text Area Field Component
version: 0.0.1
repository: https://github.com/simple-dart/text_area_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2

